# Generated by Django 2.0.12 on 2019-09-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
